<?php

// Second exercise

class Beer extends Beverage {
var string $name;
var float $alcoholpercentage;

public function __construct(string $color, float $price, string $name, float $alcoholpercentage, string $temperature = "cold") {
$this->name = $name;
$this->alcoholpercentage = $alcoholpercentage;
parent::__construct($color, $price, $temperature);
}

/**
* @return float
*/
public function getAlcoholpercentage(): float
{
return $this->alcoholpercentage . "%";
}

/**
* @return string
*/
public function getName(): string
{
return $this->name;
}
public function getInfo() {
return parent::getInfo() . "and has a " . $this->alcoholpercentage  . "% alcohol"; // TODO: Change the autogenerated stub
}
}

$duvel = new Beer("blond", 3.5, "Duvel", 8.5);

echo $duvel->getInfo().PHP_EOL;

echo $duvel->getAlcoholpercentage().PHP_EOL;
