<?php
class Beverage {
    // Properties
    var string $color;
    var float $price;
    var string $temperature = 'cold';

    public function __construct(string $color, float $price, string $temperature = "cold") {
        $this->color = $color;
        $this->price = $price;
        $this->temperature = $temperature;
    }
    // Methods

    public function getInfo() {
        return "This beverage is " . $this->temperature . " and is " . $this->color . " " ;
    }
}

$cola = new Beverage("black", 2);

/*echo $cola->getInfo();
echo "<br>";
echo $cola->temperature;*/



// Second exercise

class Beer extends Beverage {
var string $name;
var float $alcoholpercentage;

public function __construct(string $color, float $price, string $name, float $alcoholpercentage, string $temperature = "cold") {
$this->name = $name;
$this->alcoholpercentage = $alcoholpercentage;
parent::__construct($color, $price, $temperature);
}

/**
* @return float
*/
public function getAlcoholpercentage(): float
{
return $this->alcoholpercentage . "%";
}

/**
* @return string
*/
public function getName(): string
{
return $this->name;
}
public function getInfo() {
return parent::getInfo() . "and has a " . $this->alcoholpercentage  . "% alcohol"; // TODO: Change the autogenerated stub
}
}

$duvel = new Beer("blond", 3.5, "Duvel", 8.5);

echo $duvel->getInfo();
echo "<br>";
echo $duvel->alcoholpercentage;
echo "<br>";
echo $duvel->getAlcoholpercentage();


